services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
      - ./jenkins/jobs:/var/jenkins_home/jobs
      - ./jenkins/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: >
      bash -c "
        jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt &&
        /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
    restart: unless-stopped

volumes:
  jenkins_home:
